### PR TITLE
Update to bitflags 2.4.2

### PR DESCRIPTION
**Pull request by james7132**
## Checklist

- [ ] `cargo clippy` reports no issues
- [ ] `cargo doc` reports no issues
- [ ] [`cargo deny`](https://github.com/EmbarkStudios/cargo-deny/) issues have been fixed or added to `deny.toml`
- [ ] `cargo test` shows all tests passing
- [ ] human-readable change descriptions added to the changelog under the "Unreleased" heading.
  - [ ] If the change does not affect the user (or is a process change), preface the change with "Internal:"
  - [ ] Add credit to yourself for each change: `Added new functionality @githubname`.

## Description
Update to the latest version of the only dependency this crate has.

Might be a good idea to enable Dependabot this repo.

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
Nice! Will do!

**Comment by cwfitzgerald** [comment]
Have a few compilation issues

**Comment by james7132** [comment]
@cwfitzgerald, fixed!

**Comment by cwfitzgerald** [comment]
Nice!

**Comment by james7132** [comment]
Oh this is probably a breaking change, so this likely shouldn't be published without a minor version increase.

**Pull request merged**
